name: Manage S3 & cloudfront

on:
  workflow_dispatch:
    inputs:
      aws-region:
        description: 'AWS Region to deploy'
        required: true
      action:
        description: 'Action to perform (apply/destroy)'
        required: true

jobs:
  apply_cluster:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'apply' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
        aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
        aws-region: us-east-1
    - name: Terraform Init
      run: terraform init
    - name: Terraform Format
      run: terraform fmt
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Apply
      run: terraform apply -var region=${{ github.event.inputs.aws-region }} -var-file=terraform.tfvars -auto-approve
      

  destroy_cluster:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'destroy' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
        aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
        aws-region: us-east-1
    - name: Terraform Init
      run: terraform init
    - name: Terraform FMT
      run: terraform fmt
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Destroy
      run: terraform destroy -var region=${{ github.event.inputs.aws-region }} -var-file=terraform.tfvars -auto-approve
    




  
